# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: familygame.club android的另一个方案
email: machangkun@gmail.com
description: android有各种不如人意的地方, 我们一起, 一个一个, 解决他们. 是让它运行更好.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://familygame.club" # the base hostname & protocol for your site
twitter_username: lornally
github_username:  lornally

# Build settings
markdown: kramdown
